addons:
    code_climate:
        repo_token: 2a3d383bfff69919569efd114d7e61d881dfdab1aac3728308fefa65ee01809d
language: php
php:
  - '7.0'
before_script:
  - mkdir -p build/logs/
script: 
  - composer install --no-interaction --dev
  - pwd
  - vendor/bin/phpunit --debug --coverage-clover builds/logs/clover.xml --whitelist src
  - CODECLIMATE_REPO_TOKEN=2a3d383bfff69919569efd114d7e61d881dfdab1aac3728308fefa65ee01809d ./vendor/bin/test-reporter
notifications:
  on_success: change
  on_failure: change
