language: php
php:
  - '7.0'
before_script:
  - mkdir -p build/logs/
script: 
  - composer install --no-interaction --dev
  - pwd
  - vendor/bin/phpunit --debug
notifications:
  on_success: change
  on_failure: change
